### ISSUE TITLE
Is there supposed to be a client option for Cover?

### ISSUE THREAD

**Issue by linuxkidd** [ASCOMInitiative/ASCOMRemote#15]
Installed ASCOM 6.5RC2 and ASCOM Remote 1.6.7424.28304.  I see in the 'Remote Server' lists a Cover device, but the 'Remote Client Configuration' dialog doesn't have a Cover option. 

Am I missing something?

**Comment by linuxkidd** [comment]
@Peter-Simpson I don't think your update came through the way you intended... :)

**Comment by Peter-Simpson** [comment]
Hi Michael,

Very sorry, I really have no idea how this happened, nor the same on #16!

Platform 6.5 has a new feature called "Dynamic Clients" that do much the same job as the Remote Clients". The Dynamic Clients can be created on demand through the Chooser's new Alpaca menu. 

Rather than maintain these two two different approaches, we've decided to stop adding new features to the Remote Clients and just to concentrate on developing the Dynamic Clients in future. CoverCalibrators are a new device type and this is why support only appears in the Dynamic Clients.

Here is a link showing how to use Dynamic Clients, hopefully this is what you are looking for. https://ascom-standards.org/platform65rchelp/html/e3870a2f-582a-4ab4-b37f-e9b1c37a2030.htm 

Best wishes, Peter

**Comment by linuxkidd** [comment]
Hi Peter, thanks for these details.  Makes complete sense.  I consider this resolved.
