### ISSUE TITLE
EquatorialCoordinateType.equTopocentric doesn't exist, perhaps  EquatorialCoordinateType.equLocalTopocentric was intended?

### ISSUE THREAD

**Issue by mitchmitchell** [ASCOMInitiative/ASCOMRemote#5]
Line 3400 of ServerForm.cs function ReturnEquatorialSystem attempts to set deviceResponse to EquatorialCoordinateType.equTopocentric which doesn't exist in the enum definition for EquatorialCoordinateType -- possibly what is meant is:  equLocalTopocentric?

**Comment by Peter-Simpson** [comment]
Hi Mitch,

equLocalTopocentric has been deprecated in favour of equTopocentric because topocentric already implies "local". Using the term "LocalTopocentric" is like saying "local local position".

The change is documented here: https://ascom-standards.org/Help/Platform/html/T_ASCOM_DeviceInterface_EquatorialCoordinateType.htm 

Regards Peter 

⁣Sent from BlueMail ​

**Comment by mitchmitchell** [comment]
Nonetheless,  the solution refused to compile when cloned from the repository because the enumeration did not define equTopocentric.  So I guess the definition needs to be added to the enumeration declaration.



Sent via the Samsung Galaxy Note8, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by Peter-Simpson** [comment]
Hi Mitch,

equTopocentric was added to the enumeration in June 2018, are you using the latest Platform Developer Components release?

Regards, Peter

**Comment by Peter-Simpson** [comment]
Closed on the basis of no feedback as to whether using the current developer tools fixed the issue.
